version: '3'

services:
  web:
    build: .
    command: python cv_App/manage.py runserver 0.0.0.0:8002
    volumes:
      - .:/code
      - /var/log/cvapp:/var/log/cvapp
    ports:
      - "8002:8002"
  converter:
    image: "openlabs/docker-wkhtmltopdf-aas"
    ports:
      - "8010:80"
