# Generated by Django 2.2.4 on 2019-08-23 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dbtemplates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='TextTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Texts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvAppMain.Languages')),
                ('text_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvAppMain.TextTypes')),
            ],
        ),
        migrations.CreateModel(
            name='RecruitingCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('codename', models.CharField(blank=True, max_length=64)),
                ('active', models.BooleanField(default=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbtemplates.Template')),
                ('texts', models.ManyToManyField(to='cvAppMain.Texts')),
            ],
        ),
    ]
