# Generated by Django 2.2.4 on 2019-09-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvAppMain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='markdown',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='pic',
            field=models.ImageField(upload_to='static/pics'),
        ),
    ]
