# Generated by Django 2.2.4 on 2020-01-29 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvAppMain', '0002_auto_20190901_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='title',
            field=models.CharField(default='a', max_length=64),
            preserve_default=False,
        ),
    ]
