# Generated by Django 2.2.4 on 2020-01-29 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvAppMain', '0003_text_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitingcompany',
            name='lock_pdf',
            field=models.BooleanField(default=True),
        ),
    ]
