# Generated by Django 2.2.4 on 2020-02-05 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cvAppMain', '0004_recruitingcompany_lock_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='language',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cvAppMain.Language'),
        ),
    ]
