# Generated by Django 2.2.12 on 2020-05-18 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvAppMain', '0006_historicaltext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltext',
            name='markdown',
        ),
        migrations.RemoveField(
            model_name='text',
            name='markdown',
        ),
    ]
