# Generated by Django 2.2.12 on 2020-05-19 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cvAppMain', '0007_auto_20200518_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruitingcompany',
            name='lock_pdf',
        ),
        migrations.CreateModel(
            name='GeneratedPDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='pdfs')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvAppMain.RecruitingCompany')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvAppMain.Language')),
            ],
        ),
    ]
