# Generated by Django 2.2.12 on 2020-05-22 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvAppMain', '0007_auto_20200518_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruitingcompany',
            name='lock_pdf',
        ),
    ]
