# Generated by Django 2.2.12 on 2020-05-22 10:01

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('dbtemplates', '0001_initial'),
        ('cvAppMain', '0008_remove_recruitingcompany_lock_pdf'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecruitingCompany',
            new_name='RecruitmentProcess',
        ),
    ]
