# Generated by Django 2.2.12 on 2020-05-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbtemplates', '0001_initial'),
        ('cvAppMain', '0008_auto_20200519_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentAgency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('contact_persons', models.CharField(max_length=255)),
                ('notes', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='RecruitingCompany',
            new_name='RecruitmentProcess',
        ),
        migrations.AlterField(
            model_name='generatedpdf',
            name='pdf',
            field=models.FileField(upload_to='pdfs/'),
        ),
        migrations.AlterUniqueTogether(
            name='generatedpdf',
            unique_together={('company', 'language')},
        ),
    ]
