# Generated by Django 2.2.12 on 2020-05-22 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvAppMain', '0010_auto_20200522_1004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruitmentprocess',
            old_name='name',
            new_name='position',
        ),
    ]
