# Generated by Django 2.2.12 on 2020-06-03 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cvAppMain', '0011_auto_20200522_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='email',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='notes',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='phone',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='historicalcontactperson',
            name='email',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='historicalcontactperson',
            name='notes',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='historicalcontactperson',
            name='phone',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='historicalrecruitmentagency',
            name='notes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='recruitingcompany',
            name='contact_persons',
            field=models.ManyToManyField(blank=True, to='cvAppMain.ContactPerson'),
        ),
        migrations.AlterField(
            model_name='recruitmentagency',
            name='contact_persons',
            field=models.ManyToManyField(blank=True, to='cvAppMain.ContactPerson'),
        ),
        migrations.AlterField(
            model_name='recruitmentagency',
            name='notes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='recruitmentprocess',
            name='benefits',
            field=models.ManyToManyField(blank=True, to='cvAppMain.Benefit'),
        ),
        migrations.AlterField(
            model_name='recruitmentprocess',
            name='document',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dbtemplates.Template'),
        ),
        migrations.AlterField(
            model_name='recruitmentprocess',
            name='my_questions',
            field=models.ManyToManyField(blank=True, to='cvAppMain.Question'),
        ),
        migrations.AlterField(
            model_name='recruitmentprocess',
            name='texts',
            field=models.ManyToManyField(blank=True, to='cvAppMain.Text'),
        ),
        migrations.AlterField(
            model_name='recruitmentprocess',
            name='their_answers',
            field=models.ManyToManyField(blank=True, to='cvAppMain.Answer'),
        ),
    ]
