# Generated by Django 2.2.12 on 2020-06-03 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cvAppMain', '0012_auto_20200603_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruitmentprocess',
            name='their_answers',
        ),
        migrations.AddField(
            model_name='answer',
            name='process',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cvAppMain.RecruitmentProcess'),
            preserve_default=False,
        ),
    ]
