# Generated by Django 2.2.12 on 2020-06-08 10:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cvAppMain', '0014_auto_20200603_1351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benefit',
            options={'ordering': ('text',)},
        ),
        migrations.AlterModelOptions(
            name='contactperson',
            options={'ordering': ('last_name', 'first_name')},
        ),
        migrations.AlterModelOptions(
            name='processlog',
            options={'ordering': ('-timestamp',)},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('text',)},
        ),
        migrations.AlterModelOptions(
            name='recruitmentagency',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='recruitmentprocess',
            name='my_questions',
        ),
        migrations.AddField(
            model_name='contactperson',
            name='linkedin',
            field=models.URLField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='historicalcontactperson',
            name='linkedin',
            field=models.URLField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='email',
            field=models.EmailField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='historicalcontactperson',
            name='email',
            field=models.EmailField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='processlog',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='recruitmentprocess',
            name='fork',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
