# Generated by Django 2.2.12 on 2020-06-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvAppMain', '0015_auto_20200608_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='text',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='historicalrecruitingcompany',
            name='location',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='historicalrecruitingcompany',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='historicalrecruitmentagency',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='processlog',
            name='log',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recruitingcompany',
            name='location',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='recruitingcompany',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recruitmentagency',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recruitmentprocess',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
