# Generated by Django 2.2.12 on 2020-06-16 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cvAppMain', '0016_auto_20200608_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitmentprocess',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dbtemplates.Template'),
        ),
    ]
