# Generated by Django 2.2.13 on 2021-05-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('cvAppMain', '0018_auto_20200709_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentprocess',
            name='companies',
            field=models.ManyToManyField(to='companies.Company'),
        ),
    ]
