# Generated by Django 2.2.13 on 2021-05-14 16:25

from django.db import migrations


def forwards(apps, schema_editor):
    CompanyType = apps.get_model('companies', 'CompanyType')
    NewCompany = apps.get_model('companies', 'Company')
    NewPerson = apps.get_model('companies', 'ContactPerson')
    RecruitmentProcess = apps.get_model('cvAppMain', 'RecruitmentProcess')
    company = CompanyType.objects.create(name="Target Company")
    agency = CompanyType.objects.create(name="Recruitment Agency")
    for each in RecruitmentProcess.objects.all().select_related(
        'recruiting_company', 'recruiting_agency',
    ).prefetch_related(
        'recruiting_company__contact_persons', 'recruiting_agency__contact_persons'
    ):
        if each.recruiting_company:
            new_recruiting_company = NewCompany.objects.create(
                    name=each.recruiting_company.name,
                    company_type=company,
                    location=each.recruiting_company.location,
                    notes=each.recruiting_company.notes
                )
            for each_person in each.recruiting_company.contact_persons.all():
                NewPerson.objects.create(
                    first_name=each_person.first_name,
                    last_name=each_person.last_name,
                    phone=each_person.phone,
                    email=each_person.email,
                    company=new_recruiting_company,
                    linkedin=each_person.linkedin,
                    notes=each_person.notes
                )
            each.companies.add(
                new_recruiting_company
            )
        if each.recruiting_agency:
            new_recruiting_agency = NewCompany.objects.create(
                name=each.recruiting_agency.name,
                company_type=agency,
                notes=each.recruiting_agency.notes
            )
            for each_person in each.recruiting_agency.contact_persons.all():
                NewPerson.objects.create(
                    first_name=each_person.first_name,
                    last_name=each_person.last_name,
                    phone=each_person.phone,
                    email=each_person.email,
                    company=new_recruiting_agency,
                    linkedin=each_person.linkedin,
                    notes=each_person.notes
                )
            each.companies.add(
                new_recruiting_agency
            )


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('cvAppMain', '0019_recruitmentprocess_companies'),
    ]

    operations = [
        migrations.RunPython(forwards),
    ]
