# Generated by Django 2.2.13 on 2021-05-14 18:08

from django.db import migrations


def forwards(apps, schema_editor):
    Picture = apps.get_model('cvAppMain', 'Picture')
    NewPicture = apps.get_model('cv_contents', 'Picture')
    for each in Picture.objects.all():
        NewPicture.objects.create(
            name=each.name,
            pic=each.pic
        )

    Text = apps.get_model('cvAppMain', 'Text')
    NewText = apps.get_model('cv_contents', 'Text')
    NewTextType = apps.get_model('cv_contents', 'TextType')
    NewLanguage = apps.get_model('cv_contents', 'Language')
    for each in Text.objects.all().select_related('text_type', 'language'):
        NewText.objects.create(
            title=each.title,
            text=each.text,
            text_type=NewTextType.objects.get_or_create(codename=each.text_type.codename),
            language=NewLanguage.objects.get_or_create(lang=each.language.lang)
        )


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('cvAppMain', '0020_migrate_companies_and_persons'),
        ('cv_contents', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards),
    ]
